// Optional direct-host nginx template for the operator plugin. Renders only;
// the operator inspects the actual ingress owner before choosing or applying it.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

function validate(cfg) {
  if (!/^[a-z0-9]{8,32}$/.test(cfg.instanceId ?? "")) throw new Error("instanceId must be 8-32 lowercase letters or digits");
  if (typeof cfg.domain !== "string" || cfg.domain.length > 253 ||
      !/^(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$/.test(cfg.domain)) throw new Error("A public hostname is required");
  if (!["localhost", "::1", ["127", "0", "0", "1"].join(".")].includes(cfg.host)) throw new Error("A loopback host is required");
  if (!Number.isInteger(cfg.port) || cfg.port < 1 || cfg.port > 65535) throw new Error("Invalid upstream port");
  for (const key of ["certificate", "privateKey", "acmeRoot"]) {
    if (typeof cfg[key] !== "string" || !/^\/[A-Za-z0-9_./-]+$/.test(cfg[key]) || cfg[key].split("/").includes(".."))
      throw new Error(`${key} must be a safe absolute path`);
  }
}

const LOOPBACK_IPV4 = ["127", "0", "0", "1"].join(".");

function proxyHeaders(indent) {
  return [
    `${indent}proxy_pass http://${LOOPBACK_IPV4}:__PORT__;`,
    `${indent}proxy_http_version 1.1;`,
    `${indent}proxy_set_header Host $host;`,
    `${indent}proxy_set_header X-Real-IP $remote_addr;`,
    `${indent}proxy_set_header X-Forwarded-For $remote_addr;`,
    `${indent}proxy_set_header X-Forwarded-Proto $scheme;`,
  ].join("\n");
}

export function renderNginx(cfg) {
  validate(cfg);
  const z = `palmagent_${cfg.instanceId}`;
  const api = `${z}_api`;
  const auth = `${z}_auth`;
  const conn = `${z}_conn`;
  const hdr = (indent) =>
    proxyHeaders(indent).replaceAll("__PORT__", String(cfg.port)).replaceAll(LOOPBACK_IPV4, cfg.host === "::1" ? "[::1]" : cfg.host);

  const zones = [
    `# Palmagent — per-IP rate/conn limits (http{} context).`,
    `limit_req_zone  $binary_remote_addr zone=${api}:10m  rate=20r/s;`,
    `limit_req_zone  $binary_remote_addr zone=${auth}:10m rate=5r/s;`,
    `limit_conn_zone $binary_remote_addr zone=${conn}:10m;`,
    "",
  ].join("\n");

  const vhost = [
    `# Palmagent vhost — generated by Palmagent operator plugin. HTTPS is mandatory.`,
    `server {`,
    `    listen 80;`,
    `    listen [::]:80;`,
    `    server_name ${cfg.domain};`,
    `    location ^~ /.well-known/acme-challenge/ { root ${cfg.acmeRoot}; }`,
    `    location / { return 308 https://${cfg.domain}$request_uri; }`,
    `}`,
    ``,
    `server {`,
    `    listen 443 ssl;`,
    `    listen [::]:443 ssl;`,
    `    server_name ${cfg.domain};`,
    ``,
    `    # Scope response codes to this vhost so multiple managed apps can coexist.`,
    `    limit_req_status 429;`,
    `    limit_conn_status 429;`,
    ``,
    `    ssl_certificate ${cfg.certificate};`,
    `    ssl_certificate_key ${cfg.privateKey};`,
    `    ssl_protocols TLSv1.2 TLSv1.3;`,
    `    ssl_session_cache shared:${z}_ssl:10m;`,
    `    ssl_session_timeout 1d;`,
    `    ssl_session_tickets off;`,
    `    add_header Strict-Transport-Security "max-age=31536000" always;`,
    ``,
    `    # Image uploads are base64 JSON; match the application's 48MB cap.`,
    `    client_max_body_size 48m;`,
    ``,
    `    # SSE: never buffer, hold the connection open. Protected by limit_conn,`,
    `    # NEVER limit_req (it's one long-lived request).`,
    `    location /api/stream {`,
    hdr("        "),
    `        proxy_buffering off;`,
    `        proxy_cache off;`,
    `        proxy_read_timeout 3600s;`,
    `        proxy_send_timeout 3600s;`,
    `        limit_conn ${conn} 30;`,
    `    }`,
    ``,
    `    # Terminal streams: authenticated WebSocket upgrade on the same origin.`,
    `    location ~ ^/api/terminals/[^/]+/stream$ {`,
    hdr("        "),
    `        proxy_set_header Upgrade $http_upgrade;`,
    `        proxy_set_header Connection "upgrade";`,
    `        proxy_buffering off;`,
    `        proxy_cache off;`,
    `        proxy_read_timeout 60s;`,
    `        proxy_send_timeout 60s;`,
    `        limit_conn ${conn} 16;`,
    `    }`,
    ``,
    `    # Crypto endpoints — tighter rate.`,
    `    location /api/auth/ {`,
    hdr("        "),
    `        limit_req zone=${auth} burst=10 nodelay;`,
    `    }`,
    ``,
    `    location /api/ {`,
    hdr("        "),
    `        limit_req zone=${api} burst=40 nodelay;`,
    `        limit_conn ${conn} 30;`,
    `    }`,
    ``,
    `    # PWA shell + assets (load-time fan-out gets a bigger burst).`,
    `    location / {`,
    hdr("        "),
    `        limit_req zone=${api} burst=80 nodelay;`,
    `    }`,
    `}`,
    ``,
  ].join("\n");

  const bootstrap = [
    `# Temporary Palmagent ACME bootstrap — never proxies the application.`,
    `server {`,
    `    listen 80;`,
    `    listen [::]:80;`,
    `    server_name ${cfg.domain};`,
    ``,
    `    location ^~ /.well-known/acme-challenge/ { root ${cfg.acmeRoot}; }`,
    `    location / {`,
    `        return 404;`,
    `    }`,
    `}`,
    ``,
  ].join("\n");

  return {
    zones: { name: `${z}-ratelimit.conf`, text: zones },
    vhost: { name: `${z}.conf`, text: vhost },
    bootstrap: {
      name: `${z}-acme-bootstrap.conf`,
      text: bootstrap,
    },
  };
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try { console.log(JSON.stringify(renderNginx(JSON.parse(readFileSync(0, "utf8"))))); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
