export const W = 480, H = 640, STEP = 1 / 30;
export const WORLD_W = W * 3, WORLD_H = H * 3, PLAYER_SCREEN_Y = H * 0.42;
export const WEAPON_SLOTS = 3, BOSS_TIME = 150, ELITE_TIMES = [55, 105] as const;
export type Point = { x: number; y: number };
export type Weapon = "bolt" | "blade" | "arc" | "mine" | "drone";
export type EvolvingWeapon = "bolt" | "blade" | "arc";
export type Passive = "reactor" | "magnet" | "boots";
export type Robot = "scout" | "bulwark" | "engineer";
export type Sector = 1 | 2 | 3;
export type Workshop = "hull" | "power" | "salvage";
export type Rig = { robot: Robot; sector: Sector; mastery: number; workshop: Record<Workshop, number> };
export type Relay = Point & { charge: number };
export type Hazard = Point & { ttl: number };
export type Upgrade = Weapon | Passive;
export type Enemy = Point & { id: number; kind: "drone" | "charger" | "sentry" | "elite" | "boss"; hp: number; max: number; clock: number; dash: number; dx: number; dy: number };
export type Bullet = Point & { id: number; vx: number; vy: number; ttl: number; damage: number; hostile: boolean; pierce: number; hit: number[]; kind?: "bolt" | "drone" };
export type Gem = Point & { id: number; value: number };
export type Mine = Point & { id: number; ttl: number; arm: number };
export type Chest = Point & { id: number };
export type Effect = Point & { kind: "hit" | "kill" | "arc" | "rail" | "blast" | "storm"; ttl: number; value: number; from?: Point; radius?: number };
export type Reward = { kind: "evolve"; weapon: EvolvingWeapon } | { kind: "upgrade"; upgrade: Upgrade } | { kind: "repair" };
export type Run = {
  version: 4; rng: number; id: number; time: number; hull: number; player: Point; invulnerable: number;
  rig: Rig; relays: Relay[]; hazards: Hazard[]; hazardClock: number; wardenDefeated: boolean;
  level: number; xp: number; nextXp: number; kills: number; upgrades: Record<Upgrade, number>;
  spawn: number; spawned: number; bolt: number; blade: number; arc: number; mine: number; drone: number;
  boss: boolean; won: boolean; eliteWave: number; elitesCleared: number;
  evolutions: Record<EvolvingWeapon, boolean>; rewards: Reward[]; chests: Chest[]; mines: Mine[];
  enemies: Enemy[]; bullets: Bullet[]; gems: Gem[]; choices: Upgrade[]; effects: Effect[];
};
