import { recoverTasks } from "../modules/tasks/application/use-cases/recover-tasks.js";
import { openDatabase } from "../platform/sqlite/connection.js";
import { SqliteSpaces } from "../modules/spaces/adapters/outbound/sqlite-spaces.js";
import { SqliteRoutines } from "../modules/routines/adapters/outbound/sqlite-routines.js";
import { SqliteAuth } from "../modules/auth/adapters/outbound/sqlite-auth.js";
import { SqliteTasks } from "../modules/tasks/adapters/outbound/sqlite-tasks.js";

/** Process-level wiring; all repositories share this connection and transaction scope. */
export class Db {
  private readonly connection;
  readonly insertRepo: SqliteSpaces["insertRepo"];
  readonly setRepoBaseRef: SqliteSpaces["setRepoBaseRef"];
  readonly getRepo: SqliteSpaces["getRepo"];
  readonly listRepos: SqliteSpaces["listRepos"];
  readonly deleteRepo: SqliteSpaces["deleteRepo"];
  readonly insertRoutine: SqliteRoutines["insertRoutine"];
  readonly updateRoutine: SqliteRoutines["updateRoutine"];
  readonly deleteRoutine: SqliteRoutines["deleteRoutine"];
  readonly getRoutine: SqliteRoutines["getRoutine"];
  readonly listRoutines: SqliteRoutines["listRoutines"];
  readonly insertRoutineRun: SqliteRoutines["insertRoutineRun"];
  readonly finishRoutineRun: SqliteRoutines["finishRoutineRun"];
  readonly hasRunningRoutine: SqliteRoutines["hasRunningRoutine"];
  readonly interruptRoutineRuns: SqliteRoutines["interruptRoutineRuns"];
  readonly listRoutineRuns: SqliteRoutines["listRoutineRuns"];
  readonly insertCredential: SqliteAuth["insertCredential"];
  readonly getCredential: SqliteAuth["getCredential"];
  readonly listCredentials: SqliteAuth["listCredentials"];
  readonly countCredentials: SqliteAuth["countCredentials"];
  readonly bumpCredentialCounter: SqliteAuth["bumpCredentialCounter"];
  readonly deleteCredential: SqliteAuth["deleteCredential"];
  readonly createSession: SqliteAuth["createSession"];
  readonly getSession: SqliteAuth["getSession"];
  readonly refreshSession: SqliteAuth["refreshSession"];
  readonly deleteSession: SqliteAuth["deleteSession"];
  readonly pruneExpiredSessions: SqliteAuth["pruneExpiredSessions"];
  readonly createEnrollToken: SqliteAuth["createEnrollToken"];
  readonly isEnrollTokenValid: SqliteAuth["isEnrollTokenValid"];
  readonly consumeEnrollToken: SqliteAuth["consumeEnrollToken"];
  readonly readMessageState: SqliteTasks["readMessageState"];
  readonly messageTaskIds: SqliteTasks["messageTaskIds"];
  readonly writeMessageState: SqliteTasks["writeMessageState"];
  readonly transaction: SqliteTasks["transaction"];
  readonly attachment: SqliteTasks["attachment"];
  readonly attachmentByDigest: SqliteTasks["attachmentByDigest"];
  readonly insertAttachment: SqliteTasks["insertAttachment"];
  readonly attachmentIds: SqliteTasks["attachmentIds"];
  readonly attachmentInventory: SqliteTasks["attachmentInventory"];
  readonly attachmentReferences: SqliteTasks["attachmentReferences"];
  readonly setAttachmentLifecycle: SqliteTasks["setAttachmentLifecycle"];
  readonly deleteAttachment: SqliteTasks["deleteAttachment"];
  readonly insertTask: SqliteTasks["insertTask"];
  readonly getTask: SqliteTasks["getTask"];
  readonly listTasks: SqliteTasks["listTasks"];
  readonly setSessionControl: SqliteTasks["setSessionControl"];
  readonly setTaskPin: SqliteTasks["setTaskPin"];
  readonly setTaskTitle: SqliteTasks["setTaskTitle"];
  readonly appendAgentEvents: SqliteTasks["appendAgentEvents"];
  readonly importSessionEvents: SqliteTasks["importSessionEvents"];
  readonly setTaskStatus: SqliteTasks["setTaskStatus"];
  readonly setTaskSession: SqliteTasks["setTaskSession"];
  readonly setTaskSettings: SqliteTasks["setTaskSettings"];
  readonly setTaskWorktree: SqliteTasks["setTaskWorktree"];
  readonly touchTask: SqliteTasks["touchTask"];
  readonly setTaskPrs: SqliteTasks["setTaskPrs"];
  readonly setTaskPendingInput: SqliteTasks["setTaskPendingInput"];
  readonly setTaskPendingApproval: SqliteTasks["setTaskPendingApproval"];
  readonly setTaskRawSeq: SqliteTasks["setTaskRawSeq"];
  readonly getTaskRawSeq: SqliteTasks["getTaskRawSeq"];
  readonly inFlightTaskIds: SqliteTasks["inFlightTaskIds"];
  readonly resetInterruptedTasks: SqliteTasks["resetInterruptedTasks"];
  readonly insertEvent: SqliteTasks["insertEvent"];
  readonly eventCursor: SqliteTasks["eventCursor"];
  readonly eventsAfterGlobal: SqliteTasks["eventsAfterGlobal"];
  readonly eventsAfterSeq: SqliteTasks["eventsAfterSeq"];
  readonly historyStart: SqliteTasks["historyStart"];
  readonly historyPage: SqliteTasks["historyPage"];
  readonly historyChanges: SqliteTasks["historyChanges"];
  readonly activityDetails: SqliteTasks["activityDetails"];
  readonly latestHistoryPage: SqliteTasks["latestHistoryPage"];
  readonly usageByAgent: SqliteTasks["usageByAgent"];
  readonly insertApproval: SqliteTasks["insertApproval"];
  readonly upsertPushSub: SqliteTasks["upsertPushSub"];
  readonly deletePushSub: SqliteTasks["deletePushSub"];
  readonly listPushSubs: SqliteTasks["listPushSubs"];
  constructor(readonly path: string) {
    this.connection = openDatabase(path);
    try {
    const spaces = new SqliteSpaces(this.connection);
    this.insertRepo = spaces.insertRepo.bind(spaces);
    this.setRepoBaseRef = spaces.setRepoBaseRef.bind(spaces);
    this.getRepo = spaces.getRepo.bind(spaces);
    this.listRepos = spaces.listRepos.bind(spaces);
    this.deleteRepo = spaces.deleteRepo.bind(spaces);
    const routines = new SqliteRoutines(this.connection);
    this.insertRoutine = routines.insertRoutine.bind(routines);
    this.updateRoutine = routines.updateRoutine.bind(routines);
    this.deleteRoutine = routines.deleteRoutine.bind(routines);
    this.getRoutine = routines.getRoutine.bind(routines);
    this.listRoutines = routines.listRoutines.bind(routines);
    this.insertRoutineRun = routines.insertRoutineRun.bind(routines);
    this.finishRoutineRun = routines.finishRoutineRun.bind(routines);
    this.hasRunningRoutine = routines.hasRunningRoutine.bind(routines);
    this.interruptRoutineRuns = routines.interruptRoutineRuns.bind(routines);
    this.listRoutineRuns = routines.listRoutineRuns.bind(routines);
    const auth = new SqliteAuth(this.connection);
    this.insertCredential = auth.insertCredential.bind(auth);
    this.getCredential = auth.getCredential.bind(auth);
    this.listCredentials = auth.listCredentials.bind(auth);
    this.countCredentials = auth.countCredentials.bind(auth);
    this.bumpCredentialCounter = auth.bumpCredentialCounter.bind(auth);
    this.deleteCredential = auth.deleteCredential.bind(auth);
    this.createSession = auth.createSession.bind(auth);
    this.getSession = auth.getSession.bind(auth);
    this.refreshSession = auth.refreshSession.bind(auth);
    this.deleteSession = auth.deleteSession.bind(auth);
    this.pruneExpiredSessions = auth.pruneExpiredSessions.bind(auth);
    this.createEnrollToken = auth.createEnrollToken.bind(auth);
    this.isEnrollTokenValid = auth.isEnrollTokenValid.bind(auth);
    this.consumeEnrollToken = auth.consumeEnrollToken.bind(auth);
    const tasks = new SqliteTasks(this.connection);
    this.readMessageState = tasks.readMessageState.bind(tasks);
    this.messageTaskIds = tasks.messageTaskIds.bind(tasks);
    this.writeMessageState = tasks.writeMessageState.bind(tasks);
    this.transaction = tasks.transaction.bind(tasks);
    this.attachment = tasks.attachment.bind(tasks);
    this.attachmentByDigest = tasks.attachmentByDigest.bind(tasks);
    this.insertAttachment = tasks.insertAttachment.bind(tasks);
    this.attachmentIds = tasks.attachmentIds.bind(tasks);
    this.attachmentInventory = tasks.attachmentInventory.bind(tasks);
    this.attachmentReferences = tasks.attachmentReferences.bind(tasks);
    this.setAttachmentLifecycle = tasks.setAttachmentLifecycle.bind(tasks);
    this.deleteAttachment = tasks.deleteAttachment.bind(tasks);
    this.insertTask = tasks.insertTask.bind(tasks);
    this.getTask = tasks.getTask.bind(tasks);
    this.listTasks = tasks.listTasks.bind(tasks);
    this.setSessionControl = tasks.setSessionControl.bind(tasks);
    this.setTaskPin = tasks.setTaskPin.bind(tasks);
    this.setTaskTitle = tasks.setTaskTitle.bind(tasks);
    this.appendAgentEvents = tasks.appendAgentEvents.bind(tasks);
    this.importSessionEvents = tasks.importSessionEvents.bind(tasks);
    this.setTaskStatus = tasks.setTaskStatus.bind(tasks);
    this.setTaskSession = tasks.setTaskSession.bind(tasks);
    this.setTaskSettings = tasks.setTaskSettings.bind(tasks);
    this.setTaskWorktree = tasks.setTaskWorktree.bind(tasks);
    this.touchTask = tasks.touchTask.bind(tasks);
    this.setTaskPrs = tasks.setTaskPrs.bind(tasks);
    this.setTaskPendingInput = tasks.setTaskPendingInput.bind(tasks);
    this.setTaskPendingApproval = tasks.setTaskPendingApproval.bind(tasks);
    this.setTaskRawSeq = tasks.setTaskRawSeq.bind(tasks);
    this.getTaskRawSeq = tasks.getTaskRawSeq.bind(tasks);
    this.inFlightTaskIds = tasks.inFlightTaskIds.bind(tasks);
    this.resetInterruptedTasks = tasks.resetInterruptedTasks.bind(tasks);
    this.insertEvent = tasks.insertEvent.bind(tasks);
    this.eventCursor = tasks.eventCursor.bind(tasks);
    this.eventsAfterGlobal = tasks.eventsAfterGlobal.bind(tasks);
    this.eventsAfterSeq = tasks.eventsAfterSeq.bind(tasks);
    this.historyStart = tasks.historyStart.bind(tasks);
    this.historyPage = tasks.historyPage.bind(tasks);
    this.historyChanges = tasks.historyChanges.bind(tasks);
    this.activityDetails = tasks.activityDetails.bind(tasks);
    this.latestHistoryPage = tasks.latestHistoryPage.bind(tasks);
    this.usageByAgent = tasks.usageByAgent.bind(tasks);
    this.insertApproval = tasks.insertApproval.bind(tasks);
    this.upsertPushSub = tasks.upsertPushSub.bind(tasks);
    this.deletePushSub = tasks.deletePushSub.bind(tasks);
    this.listPushSubs = tasks.listPushSubs.bind(tasks);
    } catch (error) { this.connection.close(); throw error; }
  }
  recoverInFlight(now: number, keep?: Set<string>): string[] { return recoverTasks(this, now, keep); }
  get isOpen() { return this.connection.open; }
  close() { this.connection.close(); }
}
