import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { homedir, userInfo } from "node:os";
import { BRANDING } from "@palmagent/shared";
import type { InstallConfig } from "./config.js";
import { setUserAutoUpdate, userConfigPath } from "./user-config.js";
import { canSudoNonInteractive, log, sudo, sudoWriteFile } from "./sh.js";
import { quoteSystemd as quote } from "./systemd.js";

export const autoUpdateService = `${BRANDING.unitBase}-update@.service`;
const legacyUpdateService = `${BRANDING.unitBase}-update.service`;
export const autoUpdateTimer = `${BRANDING.unitBase}-update.timer`;
const UNIT_DIR = "/etc/systemd/system";

export function renderAutoUpdateUnits(cfg: InstallConfig, options = { node: process.execPath, home: homedir(), configHome: dirname(userConfigPath()) }) {
  if (cfg.mode !== "package" || !cfg.pkgDir) throw new Error("automatic updates require an installed Palmagent package");
  if (cfg.user === "root") throw new Error("automatic updates must run as an unprivileged installation owner");
  if (![cfg.user, cfg.group].every((value) => /^[a-zA-Z0-9_.-]+$/.test(value))) throw new Error("invalid automatic update service identity");
  const argv = [cfg.executionNode ?? options.node, join(cfg.pkgDir, "cli.js"), "update-request", "--data-dir", cfg.dataDir];
  return {
    service: [
      "# Generated by Palmagent; configured through the settings plugin.",
      "[Unit]", "Description=Palmagent automatic update", "After=network-online.target", "Wants=network-online.target", "CollectMode=inactive-or-failed", "",
      "[Service]", "Type=oneshot", `User=${cfg.user}`, `Group=${cfg.group}`,
      `Environment=${quote(`HOME=${options.home}`)}`,
      `Environment=${quote(`PALMAGENT_HOME=${options.configHome}`)}`, `Environment=${quote(`PATH=${cfg.execPath}`)}`,
      "Environment=PALMAGENT_NON_INTERACTIVE=1",
      `ExecStart=${argv.map((arg) => quote(arg.replace(/\$/g, () => "$$"))).join(" ")}`,
      "TimeoutStartSec=30min", "",
    ].join("\n"),
  };
}

/** Keep the executor independent of the web process, with no recurring schedule. */
export function prepareUpdateService(cfg: InstallConfig): void {
  if (cfg.user !== userInfo().username || !canSudoNonInteractive()) throw new Error("update service requires installation-owner access");
  const units = renderAutoUpdateUnits(cfg);
  retireAutoUpdateTimer();
  if (!sudoWriteFile(join(UNIT_DIR, autoUpdateService), units.service) || !sudo(["systemctl", "daemon-reload"]).ok) {
    throw new Error("could not prepare the update service");
  }
}

export function retireAutoUpdateTimer(unitDir = UNIT_DIR): void {
  if (!existsSync(join(unitDir, autoUpdateTimer))) return;
  if (!sudo(["systemctl", "disable", "--now", autoUpdateTimer]).ok ||
      !sudo(["rm", "-f", join(unitDir, autoUpdateTimer)]).ok || !sudo(["systemctl", "daemon-reload"]).ok) {
    throw new Error("could not remove the legacy update timer");
  }
}

export function startRequestedUpdate(): void {
  // A unique instance cannot lose a task-completion event to an older instance
  // that has released its lock but has not finished exiting in systemd yet.
  const instance = autoUpdateService.replace("@.", `@${randomUUID()}.`);
  if (!sudo(["systemctl", "start", "--no-block", instance]).ok) throw new Error("could not start the update service");
}

export function configureAutoUpdate(cfg: InstallConfig, enabled: boolean, dryRun = false): void {
  setUserAutoUpdate(enabled, { dataDir: cfg.dataDir, dryRun: true });
  if (dryRun) {
    log.info(`[dry-run] would save automatic updates ${enabled ? "on" : "off"} and remove the legacy timer`);
    if (enabled) log.plain(renderAutoUpdateUnits(cfg).service);
    return;
  }
  if (cfg.user !== userInfo().username) throw new Error("updates must be configured by the installation owner");
  if (enabled) {
    prepareUpdateService(cfg);
    setUserAutoUpdate(true, { dataDir: cfg.dataDir });
  } else {
    // Persist the opt-out first even if removing a legacy timer fails.
    setUserAutoUpdate(false, { dataDir: cfg.dataDir });
    retireAutoUpdateTimer();
  }
}

/** Service removal preserves the user's preference for a future reinstall. */
export function removeAutoUpdateTimer(): void {
  const units = [autoUpdateTimer, autoUpdateService, legacyUpdateService].map((name) => join(UNIT_DIR, name));
  if (!units.some((path) => existsSync(path))) return;
  retireAutoUpdateTimer();
  if (!sudo(["rm", "-f", ...units]).ok) throw new Error("could not remove update units");
}
