import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { homedir, userInfo } from "node:os";
import { BRANDING } from "@palmagent/shared";
import type { InstallConfig } from "./config.js";
import { setUserAutoUpdate, userConfigPath } from "./user-config.js";
import { canSudoNonInteractive, log, sudo, sudoWriteFile } from "./sh.js";
import { quoteSystemd as quote } from "./systemd.js";

export const autoUpdateService = `${BRANDING.unitBase}-update.service`;
export const autoUpdateTimer = `${BRANDING.unitBase}-update.timer`;
const UNIT_DIR = "/etc/systemd/system";

export function renderAutoUpdateUnits(cfg: InstallConfig, options = { node: process.execPath, home: homedir(), configHome: dirname(userConfigPath()) }) {
  if (cfg.mode !== "package" || !cfg.pkgDir) throw new Error("automatic updates require an installed Palmagent package");
  if (cfg.user === "root") throw new Error("automatic updates must run as an unprivileged installation owner");
  if (![cfg.user, cfg.group].every((value) => /^[a-zA-Z0-9_.-]+$/.test(value))) throw new Error("invalid automatic update service identity");
  const argv = [options.node, join(cfg.pkgDir, "cli.js"), "update", "--pull", "--automatic", "--non-interactive", "--data-dir", cfg.dataDir];
  return {
    service: [
      "# Generated by Palmagent; configured through the settings plugin.",
      "[Unit]", "Description=Palmagent automatic update", "After=network-online.target", "Wants=network-online.target", "",
      "[Service]", "Type=oneshot", `User=${cfg.user}`, `Group=${cfg.group}`,
      `Environment=${quote(`HOME=${options.home}`)}`,
      `Environment=${quote(`PALMAGENT_HOME=${options.configHome}`)}`, `Environment=${quote(`PATH=${cfg.execPath}`)}`,
      "Environment=PALMAGENT_NON_INTERACTIVE=1",
      `ExecStart=${argv.map((arg) => quote(arg.replace(/\$/g, () => "$$"))).join(" ")}`,
      "TimeoutStartSec=30min", "",
    ].join("\n"),
    timer: [
      "# Generated by Palmagent; disabled unless explicitly enabled in settings.",
      "[Unit]", "Description=Check Palmagent updates every six hours", "",
      "[Timer]", "OnCalendar=*-*-* 00,06,12,18:00:00", "RandomizedDelaySec=15min", "Persistent=true",
      `Unit=${autoUpdateService}`, "", "[Install]", "WantedBy=timers.target", "",
    ].join("\n"),
  };
}

export function configureAutoUpdate(cfg: InstallConfig, enabled: boolean, dryRun = false): void {
  const options = { dataDir: cfg.dataDir, dryRun: true };
  setUserAutoUpdate(enabled, options); // Validate preferences before changing a timer.
  const units = enabled ? renderAutoUpdateUnits(cfg) : undefined;
  if (dryRun) {
    log.info(`[dry-run] would ${enabled ? "enable" : "disable"} ${autoUpdateTimer} and save automatic updates ${enabled ? "on" : "off"}`);
    if (units) log.plain(units.service + "\n" + units.timer);
    return;
  }
  if (cfg.user !== userInfo().username) throw new Error("automatic updates must be configured by the installation owner");
  if (enabled) {
    if (!canSudoNonInteractive()) throw new Error("automatic updates need non-interactive service-management access; settings were not enabled");
    if (!sudoWriteFile(join(UNIT_DIR, autoUpdateService), units!.service) || !sudoWriteFile(join(UNIT_DIR, autoUpdateTimer), units!.timer)) {
      throw new Error("could not install the automatic update timer; settings were not enabled");
    }
    if (!sudo(["systemctl", "daemon-reload"]).ok || !sudo(["systemctl", "enable", "--now", autoUpdateTimer]).ok) {
      throw new Error("could not activate the automatic update timer; inspect its status");
    }
    setUserAutoUpdate(true, { dataDir: cfg.dataDir });
  } else {
    // Stop future attempts even if disabling the timer fails. Never kill an update
    // already in progress by stopping its service halfway through package install.
    setUserAutoUpdate(false, { dataDir: cfg.dataDir });
    if (existsSync(join(UNIT_DIR, autoUpdateTimer)) && !sudo(["systemctl", "disable", "--now", autoUpdateTimer]).ok) {
      throw new Error("automatic updates are off in settings, but the timer could not be disabled");
    }
  }
}

/** Service removal preserves the user's preference for a future reinstall. */
export function removeAutoUpdateTimer(): void {
  if (!existsSync(join(UNIT_DIR, autoUpdateTimer)) && !existsSync(join(UNIT_DIR, autoUpdateService))) return;
  if (!sudo(["systemctl", "disable", "--now", autoUpdateTimer]).ok) throw new Error("could not stop the automatic update timer");
  if (!sudo(["rm", "-f", join(UNIT_DIR, autoUpdateTimer), join(UNIT_DIR, autoUpdateService)]).ok) throw new Error("could not remove automatic update units");
}
