// nginx vhost renderer. Emits three files:
//   • a conf.d snippet with the per-IP rate-limit zones (http{} context)
//   • the permanent vhost: a pure TLS reverse proxy to the loopback web server, with the
//     SSE location un-buffered + long-timeout, a 48m body cap (image uploads),
//     and per-IP request/connection limits.
//   • a temporary ACME bootstrap vhost used only to obtain the first certificate.
//
// The application is never proxied over plaintext HTTP. The permanent port-80
// listener only redirects to HTTPS; the bootstrap listener returns 404 for the
// application while Certbot's nginx authenticator serves its challenge.
// Pure (no I/O) for testability.
import { BRANDING } from "@palmagent/shared";
import type { InstallConfig } from "./config.js";

export interface RenderedFile {
  name: string;
  text: string;
}
export interface RenderedNginx {
  zones: RenderedFile;
  vhost: RenderedFile;
  bootstrap: RenderedFile;
}

/** nginx zone/identifier-safe base (alnum + underscore). */
function zoneBase(): string {
  return BRANDING.unitBase.replace(/[^a-zA-Z0-9]+/g, "_");
}

const LOOPBACK_IPV4 = ["127", "0", "0", "1"].join(".");

function proxyHeaders(indent: string): string {
  return [
    `${indent}proxy_pass http://${LOOPBACK_IPV4}:__PORT__;`,
    `${indent}proxy_http_version 1.1;`,
    `${indent}proxy_set_header Host $host;`,
    `${indent}proxy_set_header X-Real-IP $remote_addr;`,
    `${indent}proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
    `${indent}proxy_set_header X-Forwarded-Proto $scheme;`,
  ].join("\n");
}

export function renderNginx(cfg: InstallConfig): RenderedNginx {
  const z = zoneBase();
  const api = `${z}_api`;
  const auth = `${z}_auth`;
  const conn = `${z}_conn`;
  const hdr = (indent: string) =>
    proxyHeaders(indent).replaceAll("__PORT__", String(cfg.port));

  const zones = [
    `# ${BRANDING.productName} — per-IP rate/conn limits (http{} context).`,
    `limit_req_zone  $binary_remote_addr zone=${api}:10m  rate=20r/s;`,
    `limit_req_zone  $binary_remote_addr zone=${auth}:10m rate=5r/s;`,
    `limit_conn_zone $binary_remote_addr zone=${conn}:10m;`,
    "",
  ].join("\n");

  const certDir = `/etc/letsencrypt/live/${cfg.domain}`;
  const vhost = [
    `# ${BRANDING.productName} vhost — generated by ${BRANDING.cliName}. HTTPS is mandatory.`,
    `server {`,
    `    listen 80;`,
    `    listen [::]:80;`,
    `    server_name ${cfg.domain};`,
    `    return 308 https://$host$request_uri;`,
    `}`,
    ``,
    `server {`,
    `    listen 443 ssl;`,
    `    listen [::]:443 ssl;`,
    `    server_name ${cfg.domain};`,
    ``,
    `    # Scope response codes to this vhost so multiple managed apps can coexist.`,
    `    limit_req_status 429;`,
    `    limit_conn_status 429;`,
    ``,
    `    ssl_certificate ${certDir}/fullchain.pem;`,
    `    ssl_certificate_key ${certDir}/privkey.pem;`,
    `    ssl_protocols TLSv1.2 TLSv1.3;`,
    `    ssl_session_cache shared:SSL:10m;`,
    `    ssl_session_timeout 1d;`,
    `    ssl_session_tickets off;`,
    `    add_header Strict-Transport-Security "max-age=31536000" always;`,
    ``,
    `    # Image uploads are base64 JSON; match the application's 48MB cap.`,
    `    client_max_body_size 48m;`,
    ``,
    `    # SSE: never buffer, hold the connection open. Protected by limit_conn,`,
    `    # NEVER limit_req (it's one long-lived request).`,
    `    location /api/stream {`,
    hdr("        "),
    `        proxy_buffering off;`,
    `        proxy_cache off;`,
    `        proxy_read_timeout 3600s;`,
    `        proxy_send_timeout 3600s;`,
    `        limit_conn ${conn} 30;`,
    `    }`,
    ``,
    `    # Crypto endpoints — tighter rate.`,
    `    location /api/auth/ {`,
    hdr("        "),
    `        limit_req zone=${auth} burst=10 nodelay;`,
    `    }`,
    ``,
    `    location /api/ {`,
    hdr("        "),
    `        limit_req zone=${api} burst=40 nodelay;`,
    `        limit_conn ${conn} 30;`,
    `    }`,
    ``,
    `    # PWA shell + assets (load-time fan-out gets a bigger burst).`,
    `    location / {`,
    hdr("        "),
    `        limit_req zone=${api} burst=80 nodelay;`,
    `    }`,
    `}`,
    ``,
  ].join("\n");

  const bootstrap = [
    `# Temporary ${BRANDING.productName} ACME bootstrap — never proxies the application.`,
    `server {`,
    `    listen 80;`,
    `    listen [::]:80;`,
    `    server_name ${cfg.domain};`,
    ``,
    `    location / {`,
    `        return 404;`,
    `    }`,
    `}`,
    ``,
  ].join("\n");

  return {
    zones: { name: `${BRANDING.unitBase}-ratelimit.conf`, text: zones },
    vhost: { name: `${BRANDING.unitBase}.conf`, text: vhost },
    bootstrap: {
      name: `${BRANDING.unitBase}-acme-bootstrap.conf`,
      text: bootstrap,
    },
  };
}

/** The upstream URL the vhost proxies to (handy for doctor/messages). */
export function upstreamUrl(cfg: InstallConfig): string {
  return `http://${LOOPBACK_IPV4}:${cfg.port}`;
}
