// systemd unit renderer for package and maintainer source installs.
//
// Two services: the long-lived runner (owns the
// claude/codex children + the DoS cgroup caps) and the web/SSE server (restarted
// on update; reattaches to live turns on boot). The bodies — User/Group,
// NODE_ENV, the env knobs, the DoS caps, Restart policy, Install target — match
// the supported host runtime. Two things vary by run mode:
//   • source mode: ExecStart runs `tsx src/*.ts` from a maintainer checkout
//   • package mode: ExecStart runs the bundled `node <pkg>/*.js`, and the web
//     unit gets STATIC_DIR (the bundle's relative PWA path doesn't resolve).
//
// `renderUnits` is pure (no I/O) so it can be validated without touching a host.
import { BRANDING } from "@palmagent/shared";
import type { InstallConfig } from "./config.js";

export interface RenderOpts {
  /** First-line comment. Defaults to a CLI-authored banner. */
  header?: string;
  /** Override unit filenames for deterministic render checks. */
  webUnitName?: string;
  runnerUnitName?: string;
  /** Absolute node binary for package-mode ExecStart (default: the current node). */
  nodeBin?: string;
}

export interface RenderedUnit {
  name: string;
  text: string;
}
export interface RenderedUnits {
  web: RenderedUnit;
  runner: RenderedUnit;
}

export function webUnitName(): string {
  return `${BRANDING.unitBase}.service`;
}
export function runnerUnitName(): string {
  return `${BRANDING.unitBase}-runner.service`;
}

function defaultHeader(cfg: InstallConfig): string {
  return `# Generated by ${BRANDING.cliName} — edit ${cfg.dataDir}/install.env, then re-run \`${BRANDING.cliName} setup\`.`;
}

function execStarts(
  cfg: InstallConfig,
  nodeBin: string,
): { web: string; runner: string } {
  if (cfg.mode === "source") {
    const tsx = `${cfg.repoDir}/apps/server/node_modules/.bin/tsx`;
    return {
      web: `${tsx} src/server.ts`,
      runner: `${tsx} src/runner-daemon.ts`,
    };
  }
  return {
    web: `${nodeBin} ${cfg.pkgDir}/server.js`,
    runner: `${nodeBin} ${cfg.pkgDir}/runner-daemon.js`,
  };
}

export function renderUnits(
  cfg: InstallConfig,
  opts: RenderOpts = {},
): RenderedUnits {
  const header = opts.header ?? defaultHeader(cfg);
  const webName = opts.webUnitName ?? webUnitName();
  const runnerName = opts.runnerUnitName ?? runnerUnitName();
  const nodeBin = opts.nodeBin ?? process.execPath;
  const exec = execStarts(cfg, nodeBin);
  const c = cfg.caps;

  const runner = [
    header,
    "[Unit]",
    `Description=${cfg.rpName} runner (owns the claude/codex child processes)`,
    "After=network.target",
    "",
    "[Service]",
    `User=${cfg.user}`,
    `Group=${cfg.group}`,
    `WorkingDirectory=${cfg.workingDir}`,
    "Environment=NODE_ENV=production",
    `Environment=RUNNER_SOCKET=${cfg.runnerSocket}`,
    "Environment=DISABLE_AUTOUPDATER=1",
    `Environment=PATH=${cfg.execPath}`,
    `ExecStart=${exec.runner}`,
    "Restart=always",
    "RestartSec=2",
    "# Resource caps contain the runner and all of its agent child processes.",
    `MemoryHigh=${c.memHigh}`,
    `MemoryMax=${c.memMax}`,
    `TasksMax=${c.tasksMaxRunner}`,
    `CPUQuota=${c.cpuQuota}`,
    `LimitNOFILE=${c.nofile}`,
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ];

  const web = [
    header,
    "[Unit]",
    `Description=${cfg.rpName} (${cfg.domain}) — web/SSE server`,
    `After=network.target ${runnerName}`,
    `Wants=${runnerName}`,
    "",
    "[Service]",
    `User=${cfg.user}`,
    `Group=${cfg.group}`,
    `WorkingDirectory=${cfg.workingDir}`,
    "Environment=NODE_ENV=production",
    `Environment=HOST=${cfg.host}`,
    `Environment=PORT=${cfg.port}`,
    `Environment=DISPATCH_CONCURRENCY=${cfg.concurrency}`,
    `Environment=DISPATCHER_DB=${cfg.dbPath}`,
    `Environment=RUNNER_SOCKET=${cfg.runnerSocket}`,
    "Environment=DISABLE_AUTOUPDATER=1",
    // Web Push contact, only when configured (unset ⇒ push disabled — no default).
    ...(cfg.pushSubject ? [`Environment=PUSH_SUBJECT=${cfg.pushSubject}`] : []),
    // package mode: the bundled server can't resolve the PWA via its relative
    // default, so pin it. Source mode resolves the workspace PWA itself.
    ...(cfg.mode === "package"
      ? [`Environment=STATIC_DIR=${cfg.pkgDir}/web`]
      : []),
    ...(cfg.repoRoots ? [`Environment=REPO_ROOTS=${cfg.repoRoots}`] : []),
    // Only when configured (unset ⇒ the CLI's own default ~/.claude).
    ...(cfg.claudeConfigDir
      ? [
          "# Isolates the dispatcher's headless Claude sessions from an interactively-used ~/.claude.",
          `Environment=CLAUDE_CONFIG_DIR=${cfg.claudeConfigDir}`,
        ]
      : []),
    "# In-app WebAuthn auth (replaces Authelia on this vhost). Enforced because",
    "# NODE_ENV=production; the RP identity must match the public origin.",
    `Environment=AUTH_RP_ID=${cfg.rpId}`,
    `Environment=AUTH_RP_NAME=${cfg.rpName}`,
    `Environment=AUTH_ORIGIN=${cfg.authOrigin}`,
    `Environment=PATH=${cfg.execPath}`,
    `ExecStart=${exec.web}`,
    "Restart=always",
    "RestartSec=2",
    "# A web restart does NOT touch the runner cgroup, so in-flight agent turns",
    "# survive a web update; the web server reattaches to them on boot.",
    `TasksMax=${c.tasksMaxWeb}`,
    `LimitNOFILE=${c.nofile}`,
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ];

  return {
    web: { name: webName, text: web.join("\n") },
    runner: { name: runnerName, text: runner.join("\n") },
  };
}
